---
title: "V. Pipeline for Absorbance data"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
message: false
warning: false
echo: true
output: false
toc: true
bibliography: references.bib
---

# To Do

-   bla

# Algorithm in natural language

-   Plate info list:

    -   plate number - element \<chr\>

    -   column(s) with std curve(s) - vector \<chr\>

    -   standard identity & unit - vector \<chr\> (element1 = name, element2 = unit)

    -   range of std concentration - vector \<num\>

    -   column(s) with blanc - vector \<chr\>

    -   blanc identity & unit of concentration - vector \<chr\> (element1 = name, element2 = unit)

    -   concentration of blanc - element \<num\>

    -   timestamp - date-time format (?)

    -   wavelength in nm - element \<int\>

-   vectorization of absorbance data, vectors are:

    -   plate number

    -   row

    -   column

    -   raw absorbance

    -   legend (or ID)

-   Correct absorbances for blanc

    -   Return a warning message

        -   when absorbances are below 0.05 or above 1.5

        -   give the number of wells concerned,

        -   give the max and min value of those wells

    -   case when row concerns std curve: correct std absorbances for std blanc

        -   find rows where concentration is zero (slice.min?)

        -   take average of absorbance from those rows

        -   substract to all absorbances of the std the average "zero" value and store it in a new column = "corrected_abs"

    -   case when row concerns samples: Correct sample absorbances for blanc

        -   find rows with blanc

        -   compute variation coefficient

            -   return a warning message when var.coeff \> 30%?

            -   exclude wells based on this? Or human decision?

        -   compute average of blancs

        -   substract that value to all non-standard rows and store it in column "corrected_abs"

-   Compute standard curve

    -   Operation per plate

    -   in plate df, filter rows corresponding to the std

    -   

# Code

## 1 - test import data

This is a test to get into data that is outside of the github repo.

It works - this can be done until we are ready to publish data sets –\> data private as long as possible

```{r}
library(tidyverse)
read_csv("../raw_data/2024_raw.csv")
```
