---
title: "3 Greenhouse, t2 - Import non-absorbance data"
format: 
  gfm:
    toc: true
    code-fold: true
# format: 
#   html:
#     embed-resources: true
#     toc: true
#     toc_float: true
#     code-fold: true
editor: visual
editor_options: 
  chunk_output_type: console
message: true
warning: true
echo: true
output: true
---

# To Do

- Link to a MicroResp pipeline!

# Set up

```{r}
#| message: false
#| warning: false

rm(list = ls())

library(tidyverse)
library(janitor)
```

# 1 - import data

## 1.1 - Non-absorbance data from AELab

```{r}
# import other "wet lab" raw data
raw_data_pot <- read_csv(
  "../raw_data/2024_raw.csv", show_col_types = TRUE,
  col_types = list(
    Soil = col_factor(),
    crop_diversity = col_factor(),
    CS = col_factor(),
    bloc = col_factor()
  )
  ) |> clean_names() |> 
  rename(sample_short = short) |> 
  filter(expe == "Pot")

raw_greenhouse_t2 <- raw_data_pot |> 
  filter(sampling_time == "t2") |> 
  # remove bare soil
  filter_out(cs == "B") |> 
  # correct biological unit
  mutate(biol_unit_nb = case_when(
    biol_unit_nb < 200 ~ biol_unit_nb,
    biol_unit_nb > 200 ~ biol_unit_nb - 200
  )) |> 
  arrange(biol_unit_nb) |> 
  # remove useless columns
  select(
    biol_unit_nb:sampling_time, 
    sample_name, #useful?
   starts_with(c("whc", "flush", "yd_rs"))
    )

# Check it out
raw_greenhouse_t2
```

## 1.2 - Data from CRA-W (Field)

## 1.3 - Microresp Data

Then, MicroResp data may need to be added, probably with its own pipeline

## 2 - Tidy data

For raw greenhouse data, it looks good for now

```{r}
raw_greenhouse_t2 |> str()

```

# 3 - Export

```{r}
raw_greenhouse_t2 |> write_rds("output/data/3_raw_greenhouse_t2.rds")
```
