---
title: "5 PCA and LER for t2 greenhouse"
format: 
  gfm:
    toc: true
editor: visual
editor_options: 
  chunk_output_type: console
message: true
warning: true
echo: true
output: true
---

# TO DO

# 0 - Intro

# Set up

```{r}
#| message: false
#| warning: false

# clean environment
rm(list = ls())

# packages
library(tidyverse)
library(vegan) # for rda()
library(patchwork)
library(RColorBrewer)
library(emmeans) # for post-hoc test (after ANCOVA of PMN)

# function
source("functions/plot_pca.R")

```

# 4 - PCA

## 3.1 - Check assumptions

.... UPCOMING?

## 3.2 - Run PCA

### 3.2.1 - Graphical parameters

```{r}
library(RColorBrewer)
display.brewer.all(n = 3, type = "qual")
display.brewer.pal(n = 3, name = "Accent")
cs_colors <- brewer.pal(n = 3, name = "Accent")
names(cs_colors) <- c("FB", "IC", "W")

display.brewer.all(n = 4, type = "qual")
display.brewer.pal(n = 4, name = "Set1")
soil_colors <- brewer.pal(n = 4, name = "Set1")
names(soil_colors) <- c("Conv", "Ref", "Auto", "ABC")
```

### 3.2.2 - Faba Bean

```{r}

rda_matrix_fb <- data_fb |> 
  select(
    biol_unit_nb,
    ppm_NO3, ppm_NH4, 
    #stem_per_fb, 
    height_per_fb, dw_fb_per_plant) |> 
  column_to_rownames("biol_unit_nb") |> 
  drop_na()
  
pca_fb <- pca(rda_matrix_fb, scale = TRUE)

summary(pca_fb)

screeplot(pca_fb, bstick = TRUE, npcs = length(pca_fb$CA$eig))

#biplot(pca_fb, scaling = 1, main = "PCA - scaling 1 = object relationships preserved")
biplot(pca_fb, main = "PCA FB - scaling 2 = variable relationships preserved")


```

Prepare data for plotting

```{r}
#non_pca <- greenhouse |> select(!ppm_NH4:NO3_NH4)
pot_scores <- scores(pca_fb, display = "sites", scaling = 2) 
biol_unit <- rownames(pot_scores) |> as.double()
pot_scores <- pot_scores |> 
  as_tibble() |> 
  mutate(biol_unit_nb = biol_unit)

var_scores <- scores(pca_fb, display = "species", scaling = 2)
variables <- rownames(var_scores)
var_scores <- var_scores |> 
  as_tibble() |> 
  mutate(variable = variables)

PC_percent <- pca_fb$CA$eig / sum(pca_fb$CA$eig)

data_fb_pca <- left_join(data_fb, pot_scores, by = join_by(biol_unit_nb))
```

Plot it

```{r}
#| warning: false
#dev.new()
plot_pca_fb_cs <- plot_pca(data_fb_pca, var_scores, PC_percent) +
  geom_point(aes( colour = cs)) +
  labs(title = "PCA - Faba Bean") +
  scale_color_discrete(palette = c(cs_colors["FB"], cs_colors["IC"])) 

plot_pca_fb_cs

plot_pca_fb_soil <- plot_pca(data_fb_pca, var_scores, PC_percent) +
  geom_point(aes( colour = soil, shape = cs)) +
  labs(title = "PCA - Faba Bean") +
  scale_color_discrete(palette = c(soil_colors)) 

plot_pca_fb_soil
```

### 3.2.3 - Wheat

```{r}

rda_matrix_w <- data_w |> 
  select(
    biol_unit_nb,
    ppm_NO3, ppm_NH4, 
    #till_per_w, 
    height_per_w, dw_w_per_plant) |> 
  column_to_rownames("biol_unit_nb") |> 
  drop_na()
  
pca_w <- pca(rda_matrix_w, scale = TRUE)

summary(pca_w)

screeplot(pca_w, bstick = TRUE, npcs = length(pca_w$CA$eig))

#biplot(pca_fb, scaling = 1, main = "PCA - scaling 1 = object relationships preserved")
biplot(pca_w, main = "PCA Wheat - scaling 2 = variable relationships preserved")


```

Prepare data for plotting

```{r}
#non_pca <- greenhouse |> select(!ppm_NH4:NO3_NH4)
pot_scores <- scores(pca_w, display = "sites", scaling = 2) 
biol_unit <- rownames(pot_scores) |> as.double()
pot_scores <- pot_scores |> 
  as_tibble() |> 
  mutate(biol_unit_nb = biol_unit)

var_scores <- scores(pca_w, display = "species", scaling = 2)
variables <- rownames(var_scores)
var_scores <- var_scores |> 
  as_tibble() |> 
  mutate(variable = variables)

PC_percent <- pca_w$CA$eig / sum(pca_w$CA$eig)

data_w_pca <- left_join(data_w, pot_scores, by = join_by(biol_unit_nb))
```

Plot it

```{r}
#dev.new()
plot_pca_w_cs <- plot_pca(data_w_pca, var_scores, PC_percent) +
  geom_point(aes( colour = cs)) +
  scale_color_discrete(palette = c(cs_colors["IC"], cs_colors["W"])) +
  labs(title = "PCA - Wheat")
  
#plot_pca_w_cs

plot_pca_w_soil <- plot_pca(data_w_pca, var_scores, PC_percent) +
  geom_point(aes( colour = soil, shape = cs)) +
  labs(title = "PCA - Wheat") +
  scale_color_discrete(palette = c(soil_colors)) 

plot_pca_w_soil
```

### 3.2.4 - All plots

```{r}
#| warning: false
plot_pca_fb_cs + plot_pca_w_cs + plot_layout(guides = "collect")

plot_pca_fb_soil + plot_pca_w_soil + plot_layout(guides = "collect")
```

# What now?

According to the screeplots, I shouldn't even represent the first PCA (at least not with this version with only 4 variables).

```{r}
# TEST CHUNK



```
